# Generated by Django 5.0.3 on 2024-04-28 08:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='uuid_field',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
